# This is a basic workflow to help you get started with Actions

name: ios

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-lib-ios:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: install toolchain
        run: |
          rustup target add aarch64-apple-ios
          cargo install cargo-lipo
          cargo install cbindgen
          brew update && brew install llvm unzip protobuf

      - name: build
        run: |
          # OPENSSL_DIR=/tmp/openssl-ios64 cargo lipo --release -p leaf-mobile --targets aarch64-apple-ios
          make ios

      - name: zip artifacts
        run: |
          mv target/universal/release/libleaf.a .
          mv target/universal/release/leaf.h .
          zip libleaf-ios.zip leaf.h libleaf.a

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-ios.zip
          path: libleaf-ios.zip
